config/routes.rb
Rails.application.routes.draw do
  resources :event_registrants

  get 'check_in_registrant/:id' => 'event_registrants#check_in_registrant'

  root to: 'visitors#index'
end

app/models/event_registrant.rb
class EventRegistrant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_registrants_controller.rb
class EventRegistrantsController < ApplicationController
  before_action :set_event_registrant, only: [:show, :edit, :update, :destroy]

  # GET /event_registrants
  # GET /event_registrants.json
  def index
    @event_registrants = EventRegistrant.all
  end

  # GET /event_registrants/1
  # GET /event_registrants/1.json
  def show
  end

  # GET /event_registrants/new
  def new
    @event_registrant = EventRegistrant.new
  end

  # GET /event_registrants/1/edit
  def edit
  end

  # POST /event_registrants
  # POST /event_registrants.json
  def create
    @event_registrant = EventRegistrant.new(event_registrant_params)

    respond_to do |format|
      if @event_registrant.save
        format.html { redirect_to @event_registrant, notice: 'Event registrant was successfully created.' }
        format.json { render :show, status: :created, location: @event_registrant }
      else
        format.html { render :new }
        format.json { render json: @event_registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_registrants/1
  # PATCH/PUT /event_registrants/1.json
  def update
    respond_to do |format|
      if @event_registrant.update(event_registrant_params)
        format.html { redirect_to @event_registrant, notice: 'Event registrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_registrant }
      else
        format.html { render :edit }
        format.json { render json: @event_registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_registrants/1
  # DELETE /event_registrants/1.json
  def destroy
    @event_registrant.destroy
    respond_to do |format|
      format.html { redirect_to event_registrants_url, notice: 'Event registrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_in_registrant
    er = EventRegistrant.find_by ImportID: params[:import_id]

    er.checked_in = 1
    er.checked_in_time = DateTime.now
    er.save()

    flash[:notice] = "You have checked in!"
    redirect_to :controller => :event_registrants 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_registrant
      @event_registrant = EventRegistrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_registrant_params
      params.require(:event_registrant).permit(:ImportID, :FirstName, :LastName, :Addr1, :Addr2, :City, :State, :DonorCategory, :NextAskAmount, :TotalIdentifiedAssets, :CurrentMajor1kDonor, :MajorDonorWith1MMinAssets, :MajorUnderPerformer, :MajorUnderPerformingByAmount, :AnnualDonorWith1MMinAssets, :AnnualUnderPerformer, :AnnualUnderPerformingByAmount)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_registrants_helper.rb
module EventRegistrantsHelper
end

app/views/event_registrants/_form.html.erb
<%= form_for(@event_registrant) do |f| %>
  <% if @event_registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_registrant.errors.count, "error") %> prohibited this event_registrant from being saved:</h2>

      <ul>
      <% @event_registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label(:ImportID, 'Import ID') %><br>
    <%= f.number_field :ImportID %>
  </div>
  <div class="field">
    <%= f.label(:FirstName, 'First Name') %><br>
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label(:LastName, 'Last Name') %><br>
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label(:Addr1, 'Address Line 1') %><br>
    <%= f.text_field :Addr1 %>
  </div>
  <div class="field">
    <%= f.label(:Addr2, 'Address Line 2') %><br>
    <%= f.text_field :Addr2 %>
  </div>
  <div class="field">
    <%= f.label(:City, 'City') %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label(:State, 'State') %><br>
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label(:DonorCategory, 'Donor Category') %><br>
    <%= f.text_field :DonorCategory %>
  </div>
  <div class="field">
    <%= f.label(:NextAskAmount, 'Next Ask Amount') %><br>
    <%= f.text_field :NextAskAmount %>
  </div>
  <div class="field">
    <%= f.label(:TotalIdentifiedAssets, 'Total Identified Assets') %><br>
    <%= f.text_field :TotalIdentifiedAssets %>
  </div>
  <div class="field">
    <%= f.label(:CurrentMajor1kDonor, 'Current Major 1k Donor') %><br>
    <%= f.number_field :CurrentMajor1kDonor %>
  </div>
  <div class="field">
    <%= f.label(:MajorDonorWith1MMinAssets, 'Major Donor With 1m Min Assets') %><br>
    <%= f.number_field :MajorDonorWith1MMinAssets %>
  </div>
  <div class="field">
    <%= f.label(:MajorUnderPerformer, 'Major Under Performer') %><br>
    <%= f.number_field :MajorUnderPerformer %>
  </div>
  <div class="field">
    <%= f.label(:MajorUnderPerformingByAmount, 'Under Performing By Amount') %><br>
    <%= f.number_field :MajorUnderPerformingByAmount %>
  </div>
  <div class="field">
    <%= f.label(:AnnualDonorWith1MMinAssets, 'Annual Donor With 1m Min Assets') %><br>
    <%= f.number_field :AnnualDonorWith1MMinAssets %>
  </div>
  <div class="field">
    <%= f.label(:AnnualUnderPerformer, 'Annual Under Performer') %><br>
    <%= f.number_field :AnnualUnderPerformer %>
  </div>
  <div class="field">
    <%= f.label(:AnnualUnderPerformingByAmount, 'Annual Under Performing By Amount') %><br>
    <%= f.number_field :AnnualUnderPerformingByAmount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_registrants/edit.html.erb
<h1>Editing event_registrant</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_registrant %> |
<%= link_to 'Back', event_registrants_path %>

app/views/event_registrants/index.html.erb
<h1>Registered Attendees</h1>

<div class="table-responsive">
  <table id="registrants" class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Checked In</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @event_registrants.each do |event_registrant| %>
        <tr>
          <td><%= link_to event_registrant.FirstName.to_s + " " + event_registrant.LastName.to_s, event_registrant %></td>
          <td><%= event_registrant.Addr1 %></td>
          <td><%= event_registrant.City %></td>
          <td><%= event_registrant.State %></td>
          <td>
            <% if event_registrant.checked_in %>
              <span class="glyphicon glyphicon-ok"></span>
            <% else %>
                <%= link_to 'Check in!', {controller: "event_registrants", action: "check_in_registrant", id: event_registrant.id, import_id: event_registrant.ImportID}, class: "btn btn-success checked_in" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/event_registrants/new.html.erb
<h1>New Event Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', event_registrants_path %>

app/views/event_registrants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
  <table class="table-hover table-bordered table-condensed table">
    <tr>
      <th class="potatocolumn">
        Category
      </th>
      <th>
        Value
      </th>
    </tr>

    <tr>
      <td>
        <strong>Import Id:</strong>
      </td>
      <td>
        <%= @event_registrant.ImportID %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>First Name:</strong>
      </td>
      <td>
        <%= @event_registrant.FirstName %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Last Name:</strong>
      </td>
      <td>
        <%= @event_registrant.LastName %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Address Line 1:</strong>
      </td>
      <td>
        <%= @event_registrant.Addr1 %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Address Line 2:</strong>
      </td>
      <td>
        <%= @event_registrant.Addr2 %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>City:</strong>
      </td>
      <td>
        <%= @event_registrant.City %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>State:</strong>
      </td>
      <td>
        <%= @event_registrant.State %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Donor Category:</strong>
      </td>
      <td>
        <%= @event_registrant.DonorCategory %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Next Ask Amount:</strong>
      </td>
      <td>
        <%= @event_registrant.NextAskAmount %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Total Identified Assets:</strong>
      </td>
      <td>
        <%= @event_registrant.TotalIdentifiedAssets %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Current Major 1k Donor:</strong>
      </td>
      <td>
        <% if @event_registrant.CurrentMajor1kDonor %>
          Yes
        <% else %>
          No
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Major Donor With 1m Min Assets:</strong>
      </td>
      <td>
        <% if @event_registrant.MajorDonorWith1MMinAssets %>
            Yes
        <% else %>
            No
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Major Under Performer:</strong>
      </td>
      <td>
        <% if @event_registrant.MajorUnderPerformer %>
            Yes
        <% else %>
            No
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Under Performing By Amount:</strong>
      </td>
      <td>
        <%= @event_registrant.MajorUnderPerformingByAmount %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Annual Donor With 1m Min Assets:</strong>
      </td>
      <td>
        <% if @event_registrant.AnnualDonorWith1MMinAssets %>
            Yes
        <% else %>
            No
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Annual Under Performer:</strong>
      </td>
      <td>
        <% if @event_registrant.AnnualUnderPerformer %>
            Yes
        <% else %>
            No
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Annual Under Performing By Amount:</strong>
      </td>
      <td>
        <%= @event_registrant.AnnualUnderPerformingByAmount %>
      </td>
    </tr>
   </table>
</div>

<%= link_to 'Back', event_registrants_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Registrants', :event_registrants %></li>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Otg Rails App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Otg Rails App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <br />
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>